spring:
  data:
    redis: # 基础 Redis 连接配置
      host: 192.168.1.111
      port: 6379
      password: Alone117
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20 # 最大连接数
          max-idle: 5 # 最大空闲连接数
          min-idle: 2 # 最小空闲连接数

logging:
  level:
    com.david.spring.cache.redis: DEBUG