name: Publish package to Maven Central and GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # 使用 actions/setup-java 导入 JDK 和 GPG 私钥
      - name: Set up JDK 17 with GPG
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: central
          server-username: ${{ secrets.OSSRH_USERNAME }} # 直接使用 secrets
          server-password: ${{ secrets.OSSRH_PASSWORD }} # 直接使用 secrets
          gpg-private-key: ${{ secrets.GPG_SECRET }} # setup-java 会自动导入
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }} # 私钥密码

      # 生成自定义 settings.xml
      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${env.MAVEN_USERNAME}</username>
                <password>${env.MAVEN_PASSWORD}</password>
              </server>
              <server>
                <id>github</id>
                <username>github</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 直接部署，不再手动导入 GPG 私钥
      - name: Deploy artifacts
        run: mvn --batch-mode deploy -s ~/.m2/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}