name: Maven Central Repo Deployment
on:
  release:
    types: [released]

jobs:
  publish-central:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Git Repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          server-id: central
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify GPG key imported
        run: |
          gpg --list-keys
          gpg --list-secret-keys

      - name: Publish to Maven Central
        run: mvn clean deploy -B -P release
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
