name: Publish package to Maven Central and GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1️⃣ 检出代码
      - uses: actions/checkout@v4

      # 2️⃣ 安装 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ 安装 GPG（Ubuntu Runner 默认有 gpg，但确保最新版）
      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg2

      # 4️⃣ 导入 GPG 私钥并设置信任
      - name: Import GPG key and set trust
        id: gpg
        run: |
          # 导入私钥
          echo "${{ secrets.GPG_SECRET }}" | gpg --batch --import

          # 获取导入的 key ID
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)

          echo "GPG_KEY_ID=$KEY_ID" >> $GITHUB_ENV

          # 设置永久信任
          echo -e "5\ny\n" | gpg --command-fd 0 --edit-key $KEY_ID trust

          # 验证
          gpg --list-secret-keys --keyid-format LONG

      # 5️⃣ 创建 Maven settings.xml
      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${env.MAVEN_USERNAME}</username>
                <password>${env.MAVEN_PASSWORD}</password>
              </server>
              <server>
                <id>github</id>
                <username>github</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 6️⃣ 部署 Maven artifacts
      - name: Deploy artifacts to Maven Central and GitHub Packages
        run: |
          mvn --batch-mode deploy -s ~/.m2/settings.xml \
            -Dgpg.keyname=$GPG_KEY_ID \
            -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
