name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          # 如果是 PR 事件，使用 PR 的 head SHA；否则，使用触发事件的 SHA
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}